# SPDX-FileCopyrightText: 2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2023 Visne <39844191+Visne@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2026 boomerstation <monkestation.com>
# SPDX-FileCopyrightText: 2026 nednaZ <Horse@neigh.whinny>
#
# SPDX-License-Identifier: MIT

contact_links:
  - name: Request a Feature
    url: https://discord.com/invite/monkestation
    about: Submit feature requests on our Discord server (https://discord.com/invite/monkestation).
